# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Library Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Autoencoder Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        pip install tensorflow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Compile autoencoder.py file
      run: |
        cd lib
        python autoencoder.py
        
    - name: Run autoencoderTest.py 
      run: |
        cd test
        python autoencoderTest.py
